### ISSUE TITLE
any support for raspberry pi?

### ISSUE THREAD

**Issue by YUX** [zmwangx/miller-rabin#1]
error: command 'aarch64-linux-gnu-gcc' failed with exit status 1

**Comment by zmwangx** [comment]
Hey, thanks for the report.

You uncovered a rather embarrassing oversight — I poured a lot of attention into the wheels but didn't test the sdist (?), so the sdist is missing a header and I didn't even notice. This is fixed in v1.0.1 I just released.

Now it works on my rpi 3B running raspbian buster with Python 3.7.3 (requires `libgmp-dev`, needless to say).
